import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/buffet-engine.js',import.meta.url),'utf8');
const context={globalThis:{}};vm.runInNewContext(source,context);const B=context.globalThis.BuffetEngine;

// Existing calculation and contract tests remain unchanged; the application-load test
// now inspects the v9 implementation rather than the thin entry loader.
test('side planning evaluates every selected side against selected proteins',()=>{const p=B.sidePlan({sideIds:['mac','sauerkraut','cucumber'],proteinKeys:['pmbe','polish','chicken']});assert.equal(p.length,3);assert.equal(p.find(x=>x.id==='mac').score,3);assert.equal(p.find(x=>x.id==='sauerkraut').score,3);assert.equal(p.find(x=>x.id==='cucumber').score,3);});
test('brats alias to Polish pairing makes sauerkraut a strong pairing',()=>{const p=B.sidePlan({sideIds:['sauerkraut'],proteinKeys:['brats']});assert.equal(p[0].score,3);});
test('changing side selection does not create phantom sides',()=>{const p=B.sidePlan({sideIds:['beans'],proteinKeys:['brisket']});assert.equal(p.map(x=>x.id).join('|'),'beans');});
test('core calculator passes side amount and unit together to the buffet planner',()=>{const finalSource=fs.readFileSync(new URL('../public/meatfest-final.js',import.meta.url),'utf8');assert.match(finalSource,/map\(id=>\(\{id,q:\{amount:sideQty\(id\),unit:sides\[id\]\.unit\}\}\)\)/);assert.match(finalSource,/sideBuyText\(r\.id,r\.q\.amount\)/);});
test('Cauliflower Mac core side id maps into buffet side catalog',()=>{const p=B.sidePlan({sideIds:['cauli'],proteinKeys:['pmbe'],sideRows:[{id:'cauli',q:{amount:.75,unit:'tin'}}]});assert.equal(p.length,1);assert.equal(p[0].side.name,'Cauliflower Mac');assert.equal(p[0].quantity.amount,.75);assert.equal(p[0].quantity.service.count,1);});
test('collards use a small serving bowl and tongs',()=>{const p=B.sidePlan({sideIds:['collards'],proteinKeys:['pork'],sideRows:[{id:'collards',q:{amount:1.25,unit:'recipe'}}]});assert.equal(p[0].quantity.amount,1.25);assert.equal(p[0].quantity.unit,'recipe');assert.equal(p[0].vessel.type,'bowl');assert.equal(p[0].service.method,'tongs');assert.equal(p[0].quantity.service.count,2);});
test('corn is planned as ears but served as half-ear pieces',()=>{const p=B.sidePlan({sideIds:['corn'],proteinKeys:['pork'],sideRows:[{id:'corn',q:{amount:6,unit:'ear'}}]});assert.equal(p[0].quantity.amount,6);assert.equal(p[0].quantity.unit,'ear');assert.equal(p[0].vessel.type,'chafer');assert.equal(p[0].service.method,'half-ear');assert.equal(p[0].quantity.service.count,1);});
test('Hawaiian rolls are only paired with sandwich meats',()=>{const p=B.breadPlan({breadIds:['hawaiian'],proteinKeys:['pork','chicken','brisket','ribs','pmbe'],eaters:44});assert.equal(p.length,1);assert.equal(p[0].score,3);assert.equal(p[0].quantity.pieces,16);assert.equal(p[0].quantity.packages,1);});
test('Hawaiian rolls and cornbread are general bread items',()=>{const p=B.breadPlan({breadIds:['hawaiian','cornbread'],proteinKeys:['pork','ribs']});assert.equal(p.length,2);assert.equal(p.every(x=>x.bread.category==='bread'),true);});
test('primary sausage service adds brat buns but variety service does not',()=>{const variety=B.breadPlan({breadIds:[],proteinKeys:['brats'],sausageMode:'traditional'});const primary=B.breadPlan({breadIds:[],proteinKeys:['brats'],sausageMode:'primary'});assert.equal(variety.some(x=>x.id==='bratBuns'),false);assert.equal(primary.some(x=>x.id==='bratBuns'),true);});
test('supplemental grilling meats remain separate from core proteins',()=>{assert.ok(B.SUPPLEMENTAL.burgers);assert.ok(B.SUPPLEMENTAL.hotdogs);assert.ok(B.SUPPLEMENTAL.brats);assert.ok(B.supplementalFactor(['burgers','hotdogs','brats'])<1);});
test('functional buns are added only for selected supplemental meats',()=>{const p=B.breadPlan({supplementalIds:['burgers','hotdogs'],proteinKeys:[]});assert.equal(p.map(x=>x.id).sort().join('|'),'burgerBuns|hotDogBuns');});
test('half quantities pair across foods into one physical chafer',()=>{const groups=B.physicalPlan([{type:'side',id:'mac',name:'Mac & Cheese',side:B.SIDES.mac,vessel:B.VESSELS.chafer,quantity:{amount:1,unit:'half'}},{type:'side',id:'cauliflowerMac',name:'Cauliflower Mac',side:B.SIDES.cauliflowerMac,vessel:B.VESSELS.chafer,quantity:{amount:1,unit:'half'}}]);assert.equal(groups.length,1);assert.equal(groups[0].linearIn,21);assert.equal(Array.from(groups[0].items).map(x=>x.serviceFill).join('|'),'half|half');});
test('three-quarter tin requirement uses one full-size tin filled three-quarters',()=>{const groups=B.physicalPlan([{type:'side',id:'q',name:'Q',side:B.SIDES.mac,vessel:B.VESSELS.chafer,quantity:{amount:.75,unit:'tin'}}]);assert.equal(groups.length,1);assert.equal(groups[0].items.length,1);assert.equal(groups[0].items[0].serviceFill,'full');assert.equal(groups[0].items[0].fillFraction,.75);});
test('quarter tin requirements use quarter physical tins rather than four-to-a-chafer packing',()=>{const groups=B.physicalPlan([{type:'side',id:'q1',name:'Q1',side:B.SIDES.mac,vessel:B.VESSELS.chafer,quantity:{amount:.25,unit:'tin'}},{type:'side',id:'q2',name:'Q2',side:B.SIDES.mac,vessel:B.VESSELS.chafer,quantity:{amount:.25,unit:'tin'}}]);assert.equal(groups.length,2);assert.ok(groups.every(g=>g.items.length===1));assert.ok(groups.every(g=>g.items[0].serviceFill==='quarter'));});
test('tin quantities preserve food units while packing physically into chafers',()=>{const p=B.sidePlan({sideIds:['beans'],proteinKeys:['brisket'],sideRows:[{id:'beans',q:{amount:.5,unit:'tin'}}]});assert.equal(p[0].quantity.amount,.5);assert.equal(p[0].quantity.unit,'tin');assert.equal(p[0].quantity.service.count,1);});
test('condiments use jars rather than chafers',()=>{const p=B.condimentPlan(['bbqSauce','pickles','mustard']);assert.equal(p.every(x=>x.vessel.type==='jar'),true);});
test('dessert load changes recommendation scale without changing core meat math',()=>{assert.equal(B.dessertPlan({dessertIds:['pie'],load:'light'})[0].scaleFactor,1);assert.equal(B.dessertPlan({dessertIds:['pie'],load:'heavy'})[0].scaleFactor,2);});
test('dessert station is separate from the main buffet table requirement',()=>{const p=B.plan({proteinKeys:['chicken','pork'],sideIds:['mac','coleslaw'],breadIds:['hawaiian'],condimentIds:['bbqSauce'],dessertIds:['pie','cake'],load:'moderate'});assert.equal(p.dessertStation.serviceGroups.length,2);assert.deepEqual(Array.from(p.dessertStation.tables.tables),[48]);assert.equal(p.dessertStation.tables.linearProvided,48);assert.notEqual(p.tables.linearRequired,p.dessertStation.tables.linearRequired);});
test('protein service vessels are included in physical table planning',()=>{const p=B.plan({proteinKeys:['chicken','pork','ribs','brisket','brats'],sideIds:[],breadIds:[],condimentIds:[]});assert.equal(p.serviceGroups.length,5);assert.equal(p.serviceGroups.reduce((s,g)=>s+g.linearIn,0),84);});
test('canonical Meatfest main buffet uses the fixed U-shape and explicitly flags an over-capacity full menu',()=>{assert.deepEqual(Array.from(B.TABLE_GEOMETRY.main),[72,72,72,48]);const p=B.plan({proteinKeys:['chicken','pork','pmbe','ribs','brisket','brats'],sideIds:['cucumber','coleslaw','corn','mac','beans','sauerkraut','cauli'],breadIds:['hawaiian'],condimentIds:['bbqSauce','pickles','mustard'],dessertIds:[]});assert.deepEqual(Array.from(p.tables.tables),[72,72,72,48]);assert.equal(p.tables.linearProvided,264);assert.equal(p.tables.layout.shape,'U');assert.equal(p.tables.overflow,true);});
test('buffet sequence is grouped by service zone and keeps core BBQ together',()=>{const p=B.plan({proteinKeys:['chicken','pork','pmbe','ribs','brisket','brats'],sideIds:['cucumber','mac','collards','sauerkraut'],breadIds:['hawaiian'],condimentIds:['bbqSauce']});const ids=p.sequence.map(x=>x.id);assert.equal(ids[0],'plates');assert.ok(ids.indexOf('cucumber')<ids.indexOf('chicken'));assert.ok(ids.indexOf('chicken')<ids.indexOf('pork'));assert.ok(ids.indexOf('pork')<ids.indexOf('ribs'));assert.ok(ids.indexOf('ribs')<ids.indexOf('brisket'));assert.ok(ids.indexOf('brisket')<ids.indexOf('brats'));assert.ok(ids.indexOf('hawaiian')>ids.indexOf('brats'));});
test('application loads the buffet engine and service UI',()=>{const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');assert.match(html,/src="\/buffet-engine\.js\?v=1"/);assert.match(html,/src="\/buffet-ui\.js\?v=1"/);const entry=fs.readFileSync(new URL('../public/buffet-ui.js',import.meta.url),'utf8');assert.match(entry,/BuffetEngine/);assert.match(entry,/buffet-ui-v9\.js/);const ui=fs.readFileSync(new URL('../public/buffet-ui-v9.js',import.meta.url),'utf8');assert.match(ui,/buffetServiceCard/);assert.match(ui,/buffetLayoutCard/);assert.match(ui,/SAUSAGE SERVICE/);assert.match(ui,/U-shaped main buffet/);assert.match(ui,/data-k/);assert.match(ui,/type="button"/);assert.match(ui,/aria-pressed/);assert.match(ui,/const shell=/);assert.doesNotMatch(entry,/document\.addEventListener\('click'/);});
