import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const source=fs.readFileSync(new URL('../public/buffet-engine.js',import.meta.url),'utf8');const context={globalThis:{}};vm.runInNewContext(source,context);const B=context.globalThis.BuffetEngine;

test('tin quantities preserve food units while packing physically into chafers',()=>{const p=B.sidePlan({sideIds:['beans'],proteinKeys:['brisket'],sideRows:[{id:'beans',q:{amount:.5,unit:'tin'}}]});assert.equal(p[0].quantity.amount,.5);assert.equal(p[0].quantity.unit,'tin');assert.equal(p[0].quantity.service.count,1);});
test('condiments use jars rather than chafers',()=>{const p=B.condimentPlan(['bbqSauce','pickles','mustard']);assert.equal(p.every(x=>x.vessel.type==='jar'),true);});
test('dessert load changes recommendation scale without changing core meat math',()=>{assert.equal(B.dessertPlan({dessertIds:['pie'],load:'light'})[0].scaleFactor,1);assert.equal(B.dessertPlan({dessertIds:['pie'],load:'heavy'})[0].scaleFactor,2);});
test('dessert station is separate from the main buffet table requirement',()=>{const p=B.plan({proteinKeys:['chicken','pork'],sideIds:['mac','coleslaw'],breadIds:['hawaiian'],condimentIds:['bbqSauce'],dessertIds:['pie','cake'],load:'moderate'});assert.equal(p.dessertStation.serviceGroups.length,2);assert.deepEqual(Array.from(p.dessertStation.tables.tables),[48]);assert.equal(p.dessertStation.tables.linearProvided,48);assert.notEqual(p.tables.linearRequired,p.dessertStation.tables.linearRequired);});
test('protein service vessels are included in physical table planning',()=>{const p=B.plan({proteinKeys:['chicken','pork','ribs','brisket','brats'],sideIds:[],breadIds:[],condimentIds:[]});assert.equal(p.serviceGroups.length,5);assert.equal(p.serviceGroups.reduce((s,g)=>s+g.linearIn,0),84);});
test('canonical Meatfest main buffet uses the fixed U-shape and explicitly flags an over-capacity full menu',()=>{assert.deepEqual(Array.from(B.TABLE_GEOMETRY.main),[72,72,72,48]);const p=B.plan({proteinKeys:['chicken','pork','pmbe','ribs','brisket','brats'],sideIds:['cucumber','coleslaw','corn','mac','beans','sauerkraut','cauli'],breadIds:['hawaiian'],condimentIds:['bbqSauce','pickles','mustard'],dessertIds:[]});assert.deepEqual(Array.from(p.tables.tables),[72,72,72,48]);assert.equal(p.tables.linearProvided,264);assert.equal(p.tables.layout.shape,'U');assert.equal(p.tables.overflow,true);});
test('buffet sequence is grouped by service zone and keeps core BBQ together',()=>{const p=B.plan({proteinKeys:['chicken','pork','pmbe','ribs','brisket','brats'],sideIds:['cucumber','mac','collards','sauerkraut'],breadIds:['hawaiian'],condimentIds:['bbqSauce']});const ids=p.sequence.map(x=>x.id);assert.equal(ids[0],'plates');assert.ok(ids.indexOf('cucumber')<ids.indexOf('chicken'));assert.ok(ids.indexOf('chicken')<ids.indexOf('pork'));assert.ok(ids.indexOf('pork')<ids.indexOf('ribs'));assert.ok(ids.indexOf('ribs')<ids.indexOf('brisket'));assert.ok(ids.indexOf('brisket')<ids.indexOf('brats'));assert.ok(ids.indexOf('hawaiian')>ids.indexOf('brats'));});
test('application loads the buffet engine and rebuilt service UI',()=>{const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');assert.match(html,/src="\/buffet-engine\.js\?v=1"/);assert.match(html,/src="\/buffet-ui\.js\?v=1"/);const entry=fs.readFileSync(new URL('../public/buffet-ui.js',import.meta.url),'utf8');assert.match(entry,/BuffetEngine/);assert.match(entry,/buffet-app\.js\?v=[0-9]+/);const app=fs.readFileSync(new URL('../public/buffet-app.js',import.meta.url),'utf8');for(const text of ['buffetServiceCard','buffetLayoutCard','SAUSAGE SERVICE','U-shaped main buffet','data-kind','type:\'button\'','aria-pressed'])assert.match(app,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(app,/customElements\.define\('meatfest-buffet'/);assert.doesNotMatch(entry,/document\.addEventListener\('click'/);});